apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mongodb-replicaset
  name: mongodb-replicaset-chart-keyfile
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
type: Opaque
data:
  key.txt: b0x0dVV4dmN6VmJ3a2ViRnRoT0E=
---

{{- if .Values.global.mongoSSL }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mongodb-replicaset
  name: mongodb-replicaset-ssl-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
type: Opaque
data:
  {{- with .Values.secrets }}
  ca.pem: {{ .ca_pem | quote }}
  mongodb.pem: {{ .mongodb_pem | quote }}
  client.pem: {{ .client_pem | quote }}
  {{- end }}
{{- end }}