global:
  mongoSSL: false
  storageClassName: ""

mongoLabels:

secrets:
  # Place holder for CA certificate(s)
  ca_pem: ""

  # Place holder for mongoDB certificate
  mongodb_pem: ""

  # Place holder for client certificate
  client_pem: ""

image:
  registry: docker.io
  tag: 4.2.19
  repository: harness/mongo
  pullPolicy: IfNotPresent
  digest: ""

initContainers:
  copyConfig:
    image:
      registry: docker.io
      tag: 1.35.0
      repository: busybox
      digest: ""
  install:
    image:
      registry: docker.io
      tag: 0.8
      repository: harness/mongodb-install
      digest: ""
  bootstrap:
    image:
      registry: docker.io
      tag: 4.2.19
      repository: harness/mongo
      digest: ""

mongoSecrets:
  adminUser:
    name: harness-secrets
    key: mongodbUsername
  adminPassword:
    name: harness-secrets
    key: mongodbPassword

labels: ""

annotations: ""

replicas: 1

resources:
  limits:
    cpu: 2
    memory: 4096Mi
  requests:
    cpu: 2
    memory: 4096Mi
wiredTigerCacheSizeGB: 1
mongoStorageCapacity: 200Gi

nodeSelector: {}

affinity: {}

tolerations: []
